import {TButtonTemplates} from './types';

export const ButtonTemplates: TButtonTemplates = {
  default: {
    slug: 'default',
    backgroundColor: '#032893',
    fontColor: 'white',
    borderColor: '#032893',
    padding: 10,
    width: '100%',
    fontSize: 15,
    paddingHorizontal: 10,
    borderRadius:0,
  },
  AuthButton: {
    slug: 'AuthButton',
    backgroundColor: "#000",
    fontColor: 'white',
    borderColor: '#7AF',
    padding: 10,
    width: '100%',
    fontSize: 13,
    paddingHorizontal: 0,
    borderRadius: 20,
  },
  LogoutButton: {
    slug: 'LogoutButton',
    backgroundColor: "#000",
    fontColor: 'white',
    borderColor: '#7AF',
    padding: 10,
    width: '80%',
    fontSize: 13,
    paddingHorizontal: 0,
    borderRadius: 20,
  },
  ProfileButton: {
    slug: 'LogoutButton',
    backgroundColor: "#000",
    fontColor: 'white',
    borderColor: '#7AF',
    padding: 10,
    width: '80%',
    fontSize: 13,
    paddingHorizontal: 0,
    borderRadius: 20,
  },
  NormalButton: {
    slug: 'NormalButton',
    backgroundColor: "black",
    fontColor: 'white',
    borderColor: '#7AF',
    padding: 10,
    width: '80%',
    fontSize: 13,
    paddingHorizontal: 0,
    borderRadius: 10,
  },
};
